runtime: php82  # or php81 for Laravel 9+
env: standard

instance_class: F2

env_variables:
  APP_KEY: 'base64:6J4jxxXjBOJnsnNWQtWVSVX++f+4dGOODURy4pAW5Fg='
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  APP_SERVICES_CACHE: /tmp/services.php
  APP_PACKAGES_CACHE: /tmp/packages.php
  APP_CONFIG_CACHE: /tmp/config.php
  APP_ROUTES_CACHE: /tmp/routes.php
  CACHE_DRIVER: database
  SESSION_DRIVER: database

  # Database configuration
  DB_CONNECTION: 'mysql'
  DB_PORT: '3306'

handlers:
  - url: /favicon\.ico
    static_files: public/favicon.ico
    upload: public/favicon\.ico

  - url: /robots\.txt
    static_files: public/robots.txt
    upload: public/robots\.txt

  - url: /(.*\.(css|js|map|jpg|jpeg|png|gif|svg|ico|eot|otf|ttf|woff|woff2))$
    static_files: public/\1
    upload: public/(.*\.(css|js|map|jpg|jpeg|png|gif|svg|ico|eot|otf|ttf|woff|woff2))$

  - url: /.*
    script: auto
