runtime: php82
env: standard
instance_class: F2

env_variables:
  GAE_APPLICATION_ENV: true
  GOOGLE_ENV_SECRET_NAME: "LARAVEL_ENV_FILE"

handlers:
  - url: /favicon\.ico
    static_files: public/favicon.ico
    upload: public/favicon\.ico

  - url: /robots\.txt
    static_files: public/robots.txt
    upload: public/robots\.txt

  - url: /(.*\.(css|js|map|jpg|jpeg|png|gif|svg|ico|eot|otf|ttf|woff|woff2))$
    static_files: public/\1
    upload: public/(.*\.(css|js|map|jpg|jpeg|png|gif|svg|ico|eot|otf|ttf|woff|woff2))$

  - url: /.*
    script: auto
